### ISSUE TITLE
A few bugs I guess

### ISSUE THREAD

**Issue by JamyDev** [WatchBeam/beam-interactive-node#1]
```
-------------------- Uncaught error in the tetris Robot client.

    > Error

Client options:
    {
      "remote": "192.168.0.141:3442",
      "key": "b1gwzrn4gqq76ipx",
      "channel": 1,
      "reportInterval": 20
    }

Error:
    {
      "inner": "Unknown packet ID 8 (2 bytes)"
    }

--------------------
```
And this one generally after the above one.
```
Error:
    {
      "inner": "Unknown packet ID 24 (1 bytes)"
    }
```
Seems to happen randomly:
```
Stack trace: Error: Illegal wire type for field Message.Field .tetris.Handshake.streamKey: 0 (2 expected)
    at Error (native)
    at ProtoBuf.Reflect.FieldPrototype.decode (/Users/jamy/Programming/beam/tetris-reference/node_modules/protobufjs/dist/ProtoBuf.js:3641:117)
    at ProtoBuf.Reflect.MessagePrototype.decode (/Users/jamy/Programming/beam/tetris-reference/node_modules/protobufjs/dist/ProtoBuf.js:3201:45)
    at Function.Message.decode (/Users/jamy/Programming/beam/tetris-reference/node_modules/protobufjs/dist/ProtoBuf.js:2896:37)
    at Decoder.decodePacket (/Users/jamy/Programming/beam/tetris-reference/dist/robot/proto/stream.js:151:37)
    at Decoder._write (/Users/jamy/Programming/beam/tetris-reference/dist/robot/proto/stream.js:172:31)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:288:5)
    at Decoder.Writable.write (_stream_writable.js:217:11)
    at Socket.ondata (_stream_readable.js:540:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:538:20)
```
I think the next one happens when more then one person is connected, but not sure:
```
Stack trace: Error: Illegal wire type for field Message.Field .tetris.Report.quorum: 2 (0 expected)
    at Error (<anonymous>)
    at ProtoBuf.Reflect.FieldPrototype.decode (c:\Users\Jamy\Programming\tetris-reference\node_modules\protobufjs\dist\ProtoBuf.js:3641:23)
    at ProtoBuf.Reflect.MessagePrototype.decode (c:\Users\Jamy\Programming\tetris-reference\node_modules\protobufjs\dist\ProtoBuf.js:3201:45)
    at Function.Message.decode (c:\Users\Jamy\Programming\tetris-reference\node_modules\protobufjs\dist\ProtoBuf.js:2896:37)
    at Decoder.decodePacket (c:\Users\Jamy\Programming\tetris-reference\dist\robot\proto\stream.js:151:37)
    at Decoder._write (c:\Users\Jamy\Programming\tetris-reference\dist\robot\proto\stream.js:172:31)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Decoder.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at emitReadable (_stream_readable.js:423:5)
    at readableAddChunk (_stream_readable.js:166:9)
    at Socket.Readable.push (_stream_readable.js:128:10)
    at TCP.onread (net.js:529:21)
```

**Comment by JamyDev** [comment]
> make tea and come back
That'd be plenty, yes

> Perhaps you're running an old version of tetrisd or something?
I was on the latest from git, but maybe I forgot to rebuild the protobuf stuff. I'll give that a shot.
