### ISSUE TITLE
Tetris.Robot is not a function in 0.2.3

### ISSUE THREAD

**Issue by ProbablePrime** [WatchBeam/beam-interactive-node#17]
Looks like the babel output changed somehow in 0.2.3. @Leviathan5 was having some trouble and after looking at some of his code I've reduced it to this:
```
var Tetris = require('beam-interactive-node');

var robot = new Tetris.Robot({});
```

Causes:
```
TypeError: Tetris.Robot is not a function
    at Object.<anonymous> (D:\Documents\GitHub\beam\beam-interactive-node-0.2.3\index.js:3:13
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

I have `beam-interactive-node` pinned at 0.2.0 which does work, so something introduced since then.

Thanks!

**Comment by SimonSchick** [comment]
I can see what the problem is, we upgraded babel to 6.x and apparently they dropped support for the CommonJS, we'll fix it soon.
